[workspace]

members = [
    "append",
    "contains",
    "dedupe",
    "unique",
    "index",
    "of",
    "reverse",
]

[profile.release]
debug = false
lto = true
opt-level = 'z'
panic = 'abort'
codegen-units = 1